### ISSUE TITLE
typo in display README?

### ISSUE THREAD

**Issue by frankalicious** [1Bitsy/1bitsy-examples#10]
Is the name of the display "st7735"?  
In the [README](https://github.com/1Bitsy/1bitsy-examples/blob/master/examples/1bitsy/tft-st7735/README.md) there is also ST77535R and ST773TR mentioned.

**Comment by MarkOsborne** [comment]
A good question. ST77535R is the name of the specific Sitronix TFT driver referenced in datasheet on the Adafruit site. However I have seen a basically identical datasheet from Sitronix without the R as well. And the driver is often referred to without the R.

The right fix is probably to drop R from the readme as its not helpful. TR is definitely a typo!

**Comment by MarkOsborne** [comment]
It looks like Sitronix make an S variant as well but judging by the datasheet the library code should work the same.
