### ISSUE TITLE
black_magic_probe_flash.scr is missing

### ISSUE THREAD

**Issue by schodet** [1Bitsy/1bitsy-examples#3]
It was removed here: https://github.com/libopencm3/libopencm3/commit/bd2cfc8ac4050096ce606c01371b8e5d83c0d750

**Comment by schodet** [comment]
Also, the readme file says: 
> The Makefiles of the examples are configured to use a Black Magic Probe by default, and will list possible serial ports that it found for you to choose from.

But if I type `make flash` it tries to use `openocd`.

**Comment by esden** [comment]
Thanks for pointing this out, should be fixed now. :)
